/* eslint-disable @next/next/no-page-custom-font */
import '@/styles/index.scss'
import 'material-symbols'
// import Swiper and modules styles
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/grid'

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import React from 'react'
import { Toaster } from 'react-hot-toast'

const nunito = Nunito({ subsets: ['latin', 'vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi">
      <head>
        <link
          rel="icon"
          href="/assets/favicon.png"
        />
      </head>
      <body className={`max-w-[100vw] max-h-[100vh] ${nunito.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
